version: '3.4'

services:
  postgres_image:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wines
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ~/volumes/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432